In [3]:
# 多元线性前提
'''
线性，自变量和因变量的关系应该是线性的，
自变量之间应该是相互独立的，不然会引发多重共线性

1. 我们需要选择合适变量 ，通过向前选择或者向后选择，或者向前向后法。
2. 一些元素无法直接进行运算，
可以使用虚拟变量来代替，但是需要注意防止虚拟变量高度相关，
简单来说就是存在一个能被其他变量预测出来的变量
一般选取m-1个虚拟变量，来表示m个类别
'''


1.0

In [18]:
import numpy as np
import pandas as pd

dataset = pd.read_csv('data/50_Startups.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,4].values
print(dataset.head())
print(dataset.info())
print(X)
print(Y)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB
None
[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.

In [25]:
#使用虚拟变量表示类别object类型
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder = LabelEncoder()
X[:,3] = labelencoder.fit_transform(X[:,3])
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 1.0, 48, 136897.8, 471784.1],
       [0.0, 1.0, 0.0, 0.0, 47, 151377.59, 443898.53],
       [1.0, 0.0, 1.0, 0.0, 46, 101145.55, 407934.54],
       [1.0, 0.0, 0.0, 1.0, 45, 118671.85, 383199.62],
       [1.0, 0.0, 1.0, 0.0, 44, 91391.77, 366168.42],
       [1.0, 0.0, 0.0, 1.0, 42, 99814.71, 362861.36],
       [0.0, 1.0, 0.0, 0.0, 43, 147198.87, 127716.82],
       [1.0, 0.0, 1.0, 0.0, 41, 145530.06, 323876.68],
       [1.0, 0.0, 0.0, 1.0, 39, 148718.95, 311613.29],
       [0.0, 1.0, 0.0, 0.0, 40, 108679.17, 304981.62],
       [1.0, 0.0, 1.0, 0.0, 36, 110594.11, 229160.95],
       [0.0, 1.0, 0.0, 0.0, 35, 91790.61, 249744.55],
       [1.0, 0.0, 1.0, 0.0, 33, 127320.38, 249839.44],
       [0.0, 1.0, 0.0, 0.0, 32, 135495.07, 252664.93],
       [1.0, 0.0, 1.0, 0.0, 38, 156547.42, 256512.92],
       [1.0, 0.0, 0.0, 1.0, 37, 122616.84, 261776.23],
       [0.0, 1.0, 0.0, 0.0, 28, 121597.55, 264346.06],
       [1.0, 0.0, 0.0, 1.0, 34, 145077.58, 282574.31],
       [1.0, 0.

In [21]:
#躲避虚拟变量陷阱
X= X[:,1:]
X

array([[0.0, 0.0, 1.0, 48, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 47, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 46, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 45, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 44, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 42, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 43, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 41, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 39, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 40, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 36, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 35, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 33, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 32, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 38, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 37, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 28, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 34, 145077.58, 282574.31],
       [0.0, 1.0, 0.0, 31, 114175.79, 294919.57],
       [0.0, 0.0, 1.0, 30, 153514.11, 0.0],
       [1.0

In [26]:
#拆分数据集合
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
X_train

array([[1.0, 0.0, 1.0, 0.0, 15, 103057.49, 214634.81],
       [1.0, 0.0, 0.0, 1.0, 13, 85047.44, 205517.64],
       [1.0, 0.0, 1.0, 0.0, 25, 144135.98, 134050.07],
       [0.0, 1.0, 0.0, 0.0, 14, 157693.92, 210797.67],
       [1.0, 0.0, 1.0, 0.0, 31, 114175.79, 294919.57],
       [1.0, 0.0, 1.0, 0.0, 41, 145530.06, 323876.68],
       [1.0, 0.0, 1.0, 0.0, 38, 156547.42, 256512.92],
       [1.0, 0.0, 0.0, 1.0, 2, 124153.04, 1903.93],
       [1.0, 0.0, 0.0, 1.0, 1, 51743.15, 0.0],
       [1.0, 0.0, 0.0, 1.0, 20, 153032.06, 107138.38],
       [1.0, 0.0, 0.0, 1.0, 37, 122616.84, 261776.23],
       [1.0, 0.0, 1.0, 0.0, 17, 115641.28, 91131.24],
       [0.0, 1.0, 0.0, 0.0, 18, 129219.61, 46085.25],
       [0.0, 1.0, 0.0, 0.0, 28, 121597.55, 264346.06],
       [0.0, 1.0, 0.0, 0.0, 7, 96189.63, 148001.11],
       [0.0, 1.0, 0.0, 0.0, 26, 113867.3, 298664.47],
       [1.0, 0.0, 0.0, 1.0, 4, 127382.3, 35534.17],
       [1.0, 0.0, 0.0, 1.0, 39, 148718.95, 311613.29],
       [0.0, 1.0, 0.0, 0.0, 32

In [27]:
#拟合训练
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [30]:
y_pred = regressor.predict(X_test)
print(y_pred-Y_test)

[ -2466.72856358  -3194.07676543  -5770.46574308  -8196.01682593
 -19200.5843803   10788.17839868 -17090.12658432  -9306.02715316
   4414.2215637   -1107.44925959]
